# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/" # Location of requirements.txt or setup.py
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix" # Prefix indicating an update patching vulnerabilities
      include: "scope" # Include the scope of the dependency being updated
    labels:
      - "dependencies" # Label to assign to the pull request
      - "python" # Additional label specifying the ecosystem
      - "prasad" # my name
