name: Dependency-Check

on:
  pull_request:
    branches:
      - main
      - 'release/*'
      - 'feature/*'

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Download OWASP Dependency-Check
        run: |
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v8.0.0/dependency-check-8.0.0-release.zip
          unzip dependency-check-8.0.0-release.zip -d dependency-check
          export PATH=$PATH:$GITHUB_WORKSPACE/dependency-check/bin

      - name: Run Dependency-Check
        run: |
          dependency-check/bin/dependency-check.sh --project "MyProject" --scan . --format HTML --out dependency-check-report

      - name: Upload Dependency-Check Report
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-report
          path: dependency-check-report
          comment-summary-in-pr: always
